"""empty message

Revision ID: 13a97224ebca
Revises: 89b80990b616
Create Date: 2021-11-28 18:50:42.550979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13a97224ebca'
down_revision = '89b80990b616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'currently_paid')
    op.drop_column('project', 'expected_project_salary')
    op.drop_column('project', 'predicted_project_salary')
    op.drop_column('task', 'predicted_task_salary')
    op.drop_column('task', 'expected_task_salary')
    op.drop_column('task', 'currently_paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('currently_paid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('expected_task_salary', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('predicted_task_salary', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('predicted_project_salary', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('expected_project_salary', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('currently_paid', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
